### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by niftylettuce** [ide/react-native-button#10]
How can I patch this with my webpack config?

```
/node_modules/react-native-button/Button.js Line 18: Unexpected token ...
You may need an appropriate loader to handle this file type.
| var Button = React.createClass({
|   propTypes: {
|     ...TouchableOpacity.propTypes,
|     disabled: PropTypes.bool,
|     style: Text.propTypes.style,
```

**Comment by niftylettuce** [comment]
Related? https://github.com/babel/babel/issues/200

**Comment by niftylettuce** [comment]
I tried using `optional: { stage: 0 }` in my webpack/babel config but it doesn't work.

**Comment by niftylettuce** [comment]
See https://github.com/babel/babel-loader/issues/119

**Comment by niftylettuce** [comment]
See https://github.com/yannickcr/eslint-plugin-react/issues/106#issue-87514714

**Comment by niftylettuce** [comment]
See https://discuss.reactjs.org/t/spread-operator-enabled-locally-but-not-on-my-ci-server/2078

**Comment by niftylettuce** [comment]
See https://gist.github.com/dlmanning/d1bc66b50e694d8ebe82

**Comment by ide** [comment]
You're probably configuring Babel incorrectly. You need to whitelist `es7.objectRestSpread` at a minimum, and it's a good idea to enable at least the same options that RN's packager does. That's not really an issue with this repo though so closing this out.

**Comment by niftylettuce** [comment]
I did whitelist it though..
