### ISSUE TITLE
Transparency on border radius not working

### ISSUE THREAD

**Issue by niftylettuce** [ide/react-native-button#13]
There is a white background no matter what, how do I remove this?

![screen shot 2015-10-23 at 10 54 37 am](https://cloud.githubusercontent.com/assets/523141/10695942/82e27eb0-7974-11e5-9077-3b1f7e4c5669.png)

```
  button: {
    width: 300,
    height: 60,
    color: '#fff',
    backgroundColor: '#49A8A2',
    borderRadius: 20
  }
```

**Comment by feisan** [comment]
try to add {overflow: 'hidden'}
