### ISSUE TITLE
How to set vertical align center in IOS?

### ISSUE THREAD

**Issue by deju** [ide/react-native-button#24]
I added a button to view and the title is "LOG In".

<img width="374" alt="2016-01-27 1 21 07" src="https://cloud.githubusercontent.com/assets/1439939/12604691/dc077ae8-c4f8-11e5-93a8-459a990b70f7.png">

**Comment by andrewljohnson** [comment]
You can add padding or paddingTop to the button style @deju 

```
<Button containerStyle={{padding:10, height: 45}}>
```

**Comment by luisfuertes** [comment]
It doesn't run on Android.

Can add `alignItems: 'center',` to style options plz?

**Comment by jwynveen** [comment]
+1 Padding does not seem to work

**Comment by andrewljohnson** [comment]
Specify the padding in the containerStyle prop, instead of the style prop. I updated my previous comment to be accurate now.

@luisfuertes @jwynveen @deju

**Comment by andrewljohnson** [comment]
@ide maybe just close this issue now

**Comment by ide** [comment]
@andrewljohnson thanks for helping out -- closing this.
