### ISSUE TITLE
Button: propType 'containerStyle' is invalid

### ISSUE THREAD

**Issue by tomkur** [ide/react-native-button#26]
Hi, 
after upgrading from RN 0.17 to 0.19, I'm getting the following warning when using `react-native-button`:
`Warning: Button: propType 'containerStyle' is invalid; it must be a function, usually from React.PropTypes.`

**Comment by peterlazar1993** [comment]
I've made a pull request #27 to fix this.

**Comment by peterlazar1993** [comment]
@ide this issue should be fixed now

**Comment by tomkur** [comment]
Thanks for quick PR, @peterlazar1993 and for quick release, @ide

**Comment by nunobbras** [comment]
I think this is happening again for "react-native": "^0.22.2"
