### ISSUE TITLE
Slow motion

### ISSUE THREAD

**Issue by ngprnk** [ide/react-native-button#40]
By including this package and button component  IOS app runs on slow motion.

**Comment by steida** [comment]
Check whether you accidentally enabled Slow Animations in iOS simulator.

**Comment by sibelius** [comment]
@ngprnk can we close this?

**Comment by ide** [comment]
Yeah I highly doubt that this component noticeably slows down your app.

**Comment by ollyde** [comment]
For anyone else who might have slow motion stuck on. Press CMD+T to disable/enable it.
