### ISSUE TITLE
1.7.0 cause app to throw an error

### ISSUE THREAD

**Issue by SamindaVidanaPathirana** [ide/react-native-button#46]
After the latest update my code leads to an error where it woks fine with 1.6.0. Error what i'm getting is,

Element type is invalid: expected a string (for build-in components) or a class/functions (for composite components) but got: object.

**Comment by bionimic** [comment]
same!

**Comment by bionimic** [comment]
dont use **var Button = require('react-native-button');**
use **import Button from 'react-native-button';**

hope this helps you. because I just found it after I comment hahaha

**Comment by ferndopolis** [comment]
@bionimic  thanks! yeah that solved it.

**Comment by ide** [comment]
Closing; the fix is to use native JS imports instead of Node/CommonJS-style requires.
