### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by younghak-jang** [ide/react-native-button#47]
I tried the instructions but when I import Button from 'react-native-button' red screen appears. 

![image](https://cloud.githubusercontent.com/assets/10684930/18318001/7013c110-7552-11e6-8ec7-1b225520a32a.png)

tried the instructions on the red screen, also looked at https://github.com/facebook/react-native/issues/4968, but doesn't work.

Something is messed up and now I can't run any other projects on react-native. Running other projects gives me the same error message.

Any help?

**Comment by pt-br** [comment]
Your path to the module should not be right or you have not installed the module into the correct project directory

**Comment by wangyueg** [comment]
@younghak-jang I have this same issue, Did you solve it, Thank you!  node:v6.9.2 npm:3.10.9 react-native: 0.39.2

**Comment by younghak-jang** [comment]
Yes, you have to install the module in your project directory not somewhere
else. Check where you have installed it.

2016년 12월 19일 (월) 오후 4:50, wangyueg <notifications@github.com>님이 작성:

**Comment by ide** [comment]
This bug is unrelated to the Button module. Something is wrong with the packager on your computer.

**Comment by murat-mehmet** [comment]
If anyone else did everything correct and still having this issue, just close the js packager terminal and run again.
