### ISSUE TITLE
fontFamily not working on Android

### ISSUE THREAD

**Issue by xyz1hang** [ide/react-native-button#52]
Hi, thanks for writing this library. I used a TypoGraphica font on the button and it worked on iOS but not on Android. I am pretty sure I used the fonts correctly on Android as the fontFamily worked in other places in my app on Android. This is how I used it:

```
<Button
            containerStyle={styles.my_btn}
            style={{
              fontSize: 20,
              fontFamily: 'typographica',
              color: 'black'
            }}
            onPress={this.goToNext.bind(this)}>
            Press me !
 </Button>
```

I will be really appreciated If you could have a look.

Thanks

**Comment by Cygnus2112** [comment]
I ran into this issue as well. What was the solution?

**Comment by ghost** [comment]
I made it work by warpping `<Text>` element inside `<Button>`:
```
<Button><Text style={{ fontFamily: '...'}}>Let's play</Text></Button>
```
