### ISSUE TITLE
What is the purpose of _renderGroupedChildren?

### ISSUE THREAD

**Issue by pickhardt** [ide/react-native-button#6]
What's the purpose of _renderGroupedChildren?

I'm trying to include an icon in a button, so it looks like:

```
    <Button style={{color: 'green'}} onPress={this._handlePress}>
      <View>
        <Text>Click Me</Text>
        <Icon name="rocket" />
      </View>
    </Button>
```

However, Button seems to only work if you include plain text without any children, like Icon or Text.

**Comment by ide** [comment]
It was so that you could pass in separate strings that get coalesced into a single <Text> component. For example:

``` js
<Button>
  Increment count to {currentCount + 1}
</Button>
```

would create `<Text>Increment count to {currentCount + 1}</Text>` somewhere in the view hierarchy instead of having two Text components.
