### ISSUE TITLE
Would you like to use react-native-platform-touchable?

### ISSUE THREAD

**Issue by peterpme** [ide/react-native-button#66]
I would be more than happy to open up a PR!

**Comment by ide** [comment]
Sure, seems reasonable.

**Comment by ide** [comment]
Once Gesture Handler reaches 1.0, it might make sense to port this API over to work with it instead. (This would be a breaking change since you'd need Gesture Handler as a peer dependency.)

**Comment by ide** [comment]
Closing this in favor of #81
