### ISSUE TITLE
How to make a button that fills the parent container?

### ISSUE THREAD

**Issue by chetstone** [ide/react-native-button#7]
I need a button that fills the parent (basically the entire device screen) with some text in the center. I'm trying to do this with flexbox properties but since `<Button>` is evidently basically a `<Text>` element, it doesn't respond to flexbox. How would you suggest doing this (in a reasonably responsive way)?

**Comment by ide** [comment]
Easiest way for now is probably to use TouchableOpacity directly and give it flexbox styling to fill the screen.

**Comment by chetstone** [comment]
Hmm --- I just came up with a hack... setting padding to a very large number. I suspect that's not recommended practice. I'll try your suggestion.

**Comment by chetstone** [comment]
Well, when I try to use TouchableOpacity directly it works the same way as TouchableHighlight which I tried before. As soon as I put some text in the element, react-native insists I have to wrap raw text in a `<Text>` element. Then the TouchableOpacity element shrinks down to the dimensions of the text box. (Or at least the touchable area is just the text box.) So I'll go with padding for now to make the text box real huge. Thanks.

**Comment by ide** [comment]
You could put a View between the TouchableOpacity and Text.

**Comment by ide** [comment]
You can also put styles on TouchableOpacity.

**Comment by chetstone** [comment]
Yes I tried those things. No luck.

## 

May all beings be happy!

**Comment by sibelius** [comment]
@chetstone did u solved your problem? can we close this?

**Comment by chetstone** [comment]
I can't remember. Anyway I guess I'm not having a problem now.
