### ISSUE TITLE
When I installed after this package, error on react-native run-ios command

### ISSUE THREAD

**Issue by DevSanSon** [ide/react-native-button#71]
Hello, I have one question.
why the error on "react-native run-ios" command after installed the package?

![screen shot 2018-01-20 at 20 22 13](https://user-images.githubusercontent.com/30267608/35183608-1e26bf22-fe24-11e7-9f51-6467ba2e29aa.png)

so I wish to fix this error and I test to 'npm install' command. So great!, begin running "react-native run-ios" command.

But next error :(
![screen shot 2018-01-20 at 21 08 23](https://user-images.githubusercontent.com/30267608/35183742-1f1e0bb8-fe26-11e7-9cba-2c363247de4f.png)

How to fix this error? please, Help me???

**Comment by ide** [comment]
Hi @DevSanSon, this error looks unrelated to react-native-button. If you find a bug specifically with this package, feel free to open another issue.
