### ISSUE TITLE
Ability to Pass ID or Argument

### ISSUE THREAD

**Issue by ghost** [ide/react-native-button#8]
Would like to be able to pass an ID or argument to the button.  For example if I do

```
 <Button ref="MyButton" onpress={this.buttonPressed}>Hi</Button>
```

I would like to be able to reference that "MyButton" was pressed allowing me to send to a single function when having multiple buttons on a screen.

**Comment by ide** [comment]
The way you'd do this with Button is the same how you'd do it elsewhere in React by using thunks:

``` js
<Button onPress={() => { this.buttonPressed(/*whatever you want here*/) } />
<Button onPress={this.buttonPressed.bind(this, /*whatever you want here*/)} />
```
