### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'containerStyle[0].padding')

### ISSUE THREAD

**Issue by jay-jlm** [ide/react-native-button#87]
What the title says.
Once I define containerStyle this goes away, but based on the first example in README.md it is not a required property.

**Comment by ide** [comment]
@noktigula this looks related to https://github.com/ide/react-native-button/pull/86. Could you please investigate & fix this if needed?

**Comment by noktigula** [comment]
Fixed: https://github.com/ide/react-native-button/pull/88
