### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Text.propTypes.allowFontScaling')

### ISSUE THREAD

**Issue by Begmamatov** [ide/react-native-button#92]
TypeError: undefined is not an object (evaluating '_reactNative.Text.propTypes.allowFontScaling')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by hssdiv** [comment]
here are changes that I did (I used: patch-package)

<img width="562" alt="Screenshot 2022-08-11 at 11 24 53" src="https://user-images.githubusercontent.com/39644901/184093383-3e2442c7-bee8-4d9c-9812-d8c6439ed5c0.png">


error seems to disappear, but I still have others errors, so I can't confirm that it will work

**Comment by systemguy** [comment]
> 

what commands did you use ?

**Comment by ide** [comment]
Addressed by https://github.com/ide/react-native-button/pull/96
