### ISSUE TITLE
Fix for react native 0.70.1

### ISSUE THREAD

**Issue by alokraj68** [ide/react-native-button#93]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-button@2.4.0` for the project I'm working on.

🔺️🔺️🔺️ Build issue fixes for latest react native library 🔺️🔺️🔺️ 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-button/Button.js b/node_modules/react-native-button/Button.js
index fb7cf46..f776b52 100644
--- a/node_modules/react-native-button/Button.js
+++ b/node_modules/react-native-button/Button.js
@@ -6,6 +6,7 @@ import {
   TouchableOpacity,
   View,
   ViewPropTypes,
+  TextStyle
 } from 'react-native';
 
 import coalesceNonElementChildren from './coalesceNonElementChildren';
@@ -16,12 +17,12 @@ export default class Button extends Component {
   static propTypes = {
     ...TouchableOpacity.propTypes,
     accessibilityLabel: PropTypes.string,
-    allowFontScaling: Text.propTypes.allowFontScaling,
+    allowFontScaling: PropTypes.bool,
     containerStyle: ViewPropTypes.style,
     disabledContainerStyle: ViewPropTypes.style,
     disabled: PropTypes.bool,
-    style: Text.propTypes.style,
-    styleDisabled: Text.propTypes.style,
+    style: PropTypes.shape(TextStyle),
+    styleDisabled: PropTypes.shape(TextStyle),
     childGroupStyle: ViewPropTypes.style,
   };
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ide** [comment]
Could you please submit a PR?

**Comment by NewSky54** [comment]
Above fixed worked for me on `react-native: "0.70.5"`.

**Comment by arinmodi** [comment]
Yes Above Fix is working but If I want to generate an eas build for the expo app than it will automatically install the dependency, in that case we are not able to generate the apk, so how can we fix that ?

**Comment by alokraj68** [comment]
I basically rolled back my project to 0.64 and stayed there. until all the module owners do proper update, its nightmare to upgrade react native versions :(

**Comment by ide** [comment]
If this is important to you, please submit a PR that follows the codebase's conventions, explains the motivation for the change, how the change was implemented, and an explanation and evidence of your test plan.

**Comment by ide** [comment]
Addressed by https://github.com/ide/react-native-button/pull/96
